# Generated by Django 4.2.7 on 2023-12-01 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date',
        ),
    ]
