# Generated by Django 4.2.7 on 2023-12-01 20:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
