# Generated by Django 5.0.1 on 2024-01-07 03:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('code', models.CharField(max_length=5)),
                ('credit', models.CharField(max_length=5)),
                ('category', models.CharField(choices=[('Humanities', 'Humanities'), ('Social Sciences', 'Social Sciences'), ('Natural Sciences', 'Natural Sciences'), ('Mathematics and Satistics', 'Mathematics and Statistics'), ('Computer Science and Information Technology', 'Computer Science and Information Technology'), ('Engineering', 'Engineering'), ('Health Sciences', 'Health Sciences'), ('Business and Economics', 'Business and Economics'), ('Fine Arts', 'Fine Arts'), ('Law', 'Law'), ('Languages and Linguistics', 'Languages and Linguistics'), ('Architecture', 'Architecture')], max_length=100)),
                ('description', models.TextField()),
                ('availability', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], max_length=100)),
                ('courses', models.ManyToManyField(to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_registration', models.DateField(default=django.utils.timezone.now)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='itreporting.module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
