# Generated by Django 4.2.7 on 2023-11-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('code', models.CharField(max_length=5)),
                ('credit', models.CharField(max_length=5)),
                ('category', models.CharField(choices=[('Humanities', 'Humanities'), ('Social Sciences', 'Social Sciences'), ('Natural Sciences', 'Natural Sciences'), ('Mathematics and Satistics', 'Mathematics and Statistics'), ('Computer Science and Information Technology', 'Computer Science and Information Technology'), ('Engineering', 'Engineering'), ('Health Sciences', 'Health Sciences'), ('Business and Economics', 'Business and Economics'), ('Fine Arts', 'Fine Arts'), ('Law', 'Law'), ('Languages and Linguistics', 'Languages and Linguistics'), ('Architecture', 'Architecture')], max_length=100)),
                ('description', models.TextField()),
                ('availability', models.CharField(choices=[('open', 'open'), ('closed', 'closed')], max_length=100)),
            ],
        ),
    ]
