# Generated by Django 4.2.7 on 2023-11-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itreporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='availability',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], max_length=100),
        ),
    ]
