# Generated by Django 4.2.7 on 2023-12-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('itreporting', '0007_alter_course_modules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursegroup',
            name='group_ptr',
        ),
        migrations.AddField(
            model_name='module',
            name='courses',
            field=models.ManyToManyField(to='auth.group'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='CourseGroup',
        ),
    ]
