# Generated by Django 4.2.7 on 2023-12-15 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itreporting', '0008_remove_coursegroup_group_ptr_module_courses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_registration', models.DateField(default=django.utils.timezone.now)),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='itreporting.module')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
